import type { TSESTree } from '@typescript-eslint/utils';

const ISSUE_MESSAGE_PARAMETER_INDEX_ZERO = new Set([
  'base64',
  'bic',
  'bigint',
  'blob',
  'boolean',
  'creditCard',
  'cuid2',
  'date',
  'decimal',
  'digits',
  'domain',
  'email',
  'emoji',
  'empty',
  'file',
  'finite',
  'function',
  'hexadecimal',
  'hexColor',
  'imei',
  'integer',
  'ip',
  'ipv4',
  'ipv6',
  'isbn',
  'isoDate',
  'isoDateTime',
  'isoDateTimeSecond',
  'isoTime',
  'isoTimeSecond',
  'isoTimestamp',
  'isoWeek',
  'isrc',
  'jwsCompact',
  'ksuid',
  'mac',
  'mac48',
  'mac64',
  'nan',
  'nanoid',
  'never',
  'nonEmpty',
  'null',
  'number',
  'octal',
  'promise',
  'rfcEmail',
  'safeInteger',
  'slug',
  'string',
  'symbol',
  'toBigint',
  'toDate',
  'toNumber',
  'toString',
  'ulid',
  'undefined',
  'url',
  'uuid',
  'void',
]);

const ISSUE_MESSAGE_PARAMETER_INDEX_ONE = new Set([
  'array',
  'arrayAsync',
  'bytes',
  'check',
  'checkAsync',
  'checkItems',
  'checkItemsAsync',
  'codePoints',
  'custom',
  'customAsync',
  'endsWith',
  'entries',
  'enum',
  'everyItem',
  'excludes',
  'graphemes',
  'gtValue',
  'guard',
  'hash',
  'includes',
  'instance',
  'intersect',
  'intersectAsync',
  'keyof',
  'length',
  'literal',
  'looseObject',
  'looseObjectAsync',
  'looseTuple',
  'looseTupleAsync',
  'ltValue',
  'maxBytes',
  'maxCodePoints',
  'maxEntries',
  'maxGraphemes',
  'maxLength',
  'maxSize',
  'maxValue',
  'mimeType',
  'minBytes',
  'minCodePoints',
  'minEntries',
  'minGraphemes',
  'minLength',
  'minSize',
  'minValue',
  'multipleOf',
  'nonNullable',
  'nonNullableAsync',
  'nonNullish',
  'nonNullishAsync',
  'nonOptional',
  'nonOptionalAsync',
  'notBytes',
  'notCodePoints',
  'notEntries',
  'notGraphemes',
  'notLength',
  'notSize',
  'notValue',
  'notValues',
  'object',
  'objectAsync',
  'parseBoolean',
  'parseJson',
  'picklist',
  'regex',
  'required',
  'requiredAsync',
  'set',
  'setAsync',
  'size',
  'someItem',
  'startsWith',
  'strictObject',
  'strictObjectAsync',
  'strictTuple',
  'strictTupleAsync',
  'stringifyJson',
  'tuple',
  'tupleAsync',
  'union',
  'unionAsync',
  'value',
  'values',
]);

const ISSUE_MESSAGE_PARAMETER_INDEX_TWO = new Set([
  'map',
  'mapAsync',
  'maxWords',
  'minWords',
  'notWords',
  'objectWithRest',
  'objectWithRestAsync',
  'partialCheck',
  'partialCheckAsync',
  'record',
  'recordAsync',
  'tupleWithRest',
  'tupleWithRestAsync',
  'variant',
  'variantAsync',
  'words',
]);

// `required(schema, keys, message)` shifts the message argument when a keys
// array is passed. Only literal arrays are treated as keys; an identifier stays
// ambiguous and is assumed to be the message.
const KEYS_OVERLOAD_NAMES = new Set(['required', 'requiredAsync']);

export function getIssueMessageParameterIndex(
  name: string,
  args: readonly TSESTree.CallExpressionArgument[] = [],
): 0 | 1 | 2 | null {
  if (KEYS_OVERLOAD_NAMES.has(name) && args[1]?.type === 'ArrayExpression') {
    return 2;
  }

  if (ISSUE_MESSAGE_PARAMETER_INDEX_ZERO.has(name)) {
    return 0;
  }

  if (ISSUE_MESSAGE_PARAMETER_INDEX_ONE.has(name)) {
    return 1;
  }

  if (ISSUE_MESSAGE_PARAMETER_INDEX_TWO.has(name)) {
    return 2;
  }

  return null;
}
